"""create exertion table

Revision ID: 4342095c76a7
Revises: None
Create Date: 2014-04-19 12:11:25.439399

"""

# revision identifiers, used by Alembic.
revision = '4342095c76a7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exertion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('exercise', sa.String(length=25), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exertion')
    ### end Alembic commands ###
