---
- hosts: vagrant
  vars:
    - root: /srv/yoyo
  tasks:
    - name: update apt cache
      apt: update-cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade distro
      apt: upgrade=yes
      sudo: yes

    - name: install packages
      action: apt pkg={{ item }} state=installed
      with_items:
        - python-dev
        - python-pip
        - python-virtualenv
        - supervisor
        - nginx
      notify: restart nginx
      sudo: yes

    - name: create user
      action: user name=yoyo system=yes createhome=no state=present
      sudo: yes

    - name: mount sourcecode
      action: mount fstype=vboxsf opts=uid=yoyo,gid=yoyo name={{ root }} src=/vagrant state=mounted
      sudo: yes

    - name: install dependencies
      action: pip requirements={{ root }}/requirements.txt virtualenv={{ root }}/.virtualenv state=present virtualenv_site_packages=no
      notify: restart app

    - name: create /etc/supervisor/conf.d/yoyo.conf
      action: template src=templates/supervisor.conf dest=/etc/supervisor/conf.d/yoyo.conf
      notify:
        - reread supervisorctl
        - update supervisorctl
        - restart app
      sudo: yes

    - name: start supervisor
      action: service name=supervisor state=started enabled=yes
      sudo: yes

    - name: remove /etc/nginx/sites-enabled/default
      action: file path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      sudo: yes

    - name: create /etc/nginx/sites-enabled/yoyo.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/sites-enabled/yoyo.conf
      notify: restart nginx
      sudo: yes

    - name: start nginx
      action: service name=nginx state=started enabled=yes
      sudo: yes

  handlers:
    - name: reread supervisorctl
      action: command supervisorctl reread
      sudo: yes

    - name: update supervisorctl
      action: command supervisorctl update
      sudo: yes

    - name: restart app
      action: command supervisorctl restart yoyo
      sudo: yes

    - name: restart nginx
      action: service name=nginx state=restarted
      sudo: yes
