---
- hosts: vagrant
  vars:
    - root: /srv/massa
    - pg_password: secret
  tasks:
    - name: update apt cache
      apt: update-cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade distro
      apt: upgrade=yes
      sudo: yes

    - name: install packages
      action: apt pkg={{ item }} state=installed
      with_items:
        - python-dev
        - python-pip
        - python-virtualenv
        - python-psycopg2
        - supervisor
        - nginx
        - postgresql
        - postgresql-contrib
        - libpq-dev
      notify: restart nginx
      sudo: yes

    - name: create user
      action: user name=massa system=yes state=present
      sudo: yes

    - name: mount sourcecode
      action: mount fstype=vboxsf opts=uid=massa,gid=massa name={{ root }} src=/vagrant state=mounted
      sudo: yes

    - name: install dependencies
      action: pip requirements={{ root }}/requirements.txt virtualenv={{ root }}/.virtualenv state=present
      notify: restart app

    - name: create /etc/supervisor/conf.d/massa.conf
      action: template src=templates/supervisor.conf dest=/etc/supervisor/conf.d/massa.conf
      notify:
        - reread supervisorctl
        - update supervisorctl
        - restart app
      sudo: yes

    - name: start supervisor
      action: service name=supervisor state=started enabled=yes
      sudo: yes

    - name: remove /etc/nginx/sites-enabled/default
      action: file path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
      sudo: yes

    - name: create /etc/nginx/sites-enabled/massa.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/sites-enabled/massa.conf
      notify: restart nginx
      sudo: yes

    - name: start nginx
      action: service name=nginx state=started enabled=yes
      sudo: yes

    - name: create postgresql user
      action: postgresql_user name=massa password={{ pg_password}} state=present role_attr_flags=NOSUPERUSER,NOCREATEDB,NOCREATEROLE
      notify: restart postgresql
      sudo: yes
      sudo_user: postgres

    - name: create postgresql db
      action: postgresql_db name=massa owner=massa state=present encoding=UTF-8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8 template=template0
      notify: restart postgresql
      sudo: yes
      sudo_user: postgres

    - name: start postgresql
      action: service name=postgresql state=started enabled=yes
      sudo: yes

  handlers:
    - name: reread supervisorctl
      action: command supervisorctl reread
      sudo: yes

    - name: update supervisorctl
      action: command supervisorctl update
      sudo: yes

    - name: restart app
      action: command supervisorctl restart massa
      sudo: yes

    - name: restart nginx
      action: service name=nginx state=restarted
      sudo: yes

    - name: restart postgresql
      action: service name=postgresql state=restarted
      sudo: yes
